name: Render Draw.io Diagrams
on: [push]
jobs:
  render_drawio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Render .drawio files
        uses: docker://ghcr.io/racklet/render-drawio-action:v1
        with:
          formats: 'svg' # Specify output formats (e.g., svg, png)
          sub-dirs: '.'  # Subdirectories to scan for .drawio files
      - name: Commit rendered files
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Automatically render .drawio files'
          add: "${{ steps.render.outputs.rendered-files }}"
